spring:
  application:
    name: user-service

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: role_user
    password: user_db

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka